config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  
  root to: "rooms#index"
  resources :welcome, only: [:index]
  resources :rooms, only: [:index, :show]
end

app/models/game.rb
# This is the core engine of actioncable. Broadcast methods can also be placed
# in channel file instead
class Game
  def self.start(uuid1, uuid2)
    white, black = [uuid1, uuid2].shuffle

    REDIS.set("opponent_for:#{white}", black)
    REDIS.set("opponent_for:#{black}", white)

    ActionCable.server.broadcast "player_#{uuid1}", {action: "game_start", msg: "white"}
    ActionCable.server.broadcast "player_#{uuid2}", {action: "game_start", msg: "black"}
    random_letter = (65 + rand(26)).chr
    ActionCable.server.broadcast "player_#{uuid1}", {action: "add_letter", msg: {letter: random_letter, side: "right"}}
    ActionCable.server.broadcast "player_#{uuid2}", {action: "add_letter", msg: {letter: random_letter, side: "right"}}
    ActionCable.server.broadcast "player_#{uuid1}", {action: "set_turn"}
  end

  def self.forfeit(uuid)
    if winner = opponent_for(uuid)
      ActionCable.server.broadcast "player_#{winner}", {action: "opponent_forfeits"}
    end
  end

  def self.opponent_for(uuid)
    REDIS.get("opponent_for:#{uuid}")
  end

  def self.make_move(uuid, data)
    opponent = opponent_for(uuid)
    move_string = "#{data["from"]}-#{data["to"]}"

    ActionCable.server.broadcast "player_#{opponent}", {action: "make_move", msg: move_string}
  end

  def self.add_letter(uuid, data)
    opponent = opponent_for(uuid)
    ActionCable.server.broadcast "player_#{opponent}", {action: "add_letter", msg: data}
    ActionCable.server.broadcast "player_#{uuid}", {action: "add_letter", msg: data}
    if word_finished(data)
      ActionCable.server.broadcast "player_#{opponent}", {action: "won", msg: "Oponnent finished the word"}
      ActionCable.server.broadcast "player_#{uuid}", {action: "lost", msg: "You finished the word"}
    else
      ActionCable.server.broadcast "player_#{opponent}", {action: "set_turn"}
    end
  end

  def self.check_opponent(uuid, data)
    opponent = opponent_for(uuid)
    check_word(opponent, {message: "Oponnent checks!"})
  end

  def self.check_word(uuid, data)
    ActionCable.server.broadcast "player_#{uuid}", {action: "check_word", msg: data}
  end

  def self.answer_check(uuid, data)
    opponent = opponent_for(uuid)
    if !data['answer'].downcase.include? data['word'].downcase
      check_word(uuid, {message: "The answer doesnt contain current letters!"})
    elsif !Word.find_by_word(data['answer'].downcase).present?
      ActionCable.server.broadcast "player_#{uuid}", {action: "lost", msg: "word not found in dictionary"}
      ActionCable.server.broadcast "player_#{opponent}", {action: "won", msg: "oponnent did not provide correct word"}
    else
      ActionCable.server.broadcast "player_#{uuid}", {action: "won", msg: "word correct"}
      ActionCable.server.broadcast "player_#{opponent}", {action: "lost", msg: "oponnent provided correct word: #{data['answer'].downcase}"}
    end
  end

  def self.word_finished(data)
    if data['side'] == "right"
      word = "#{data['word']}#{data['letter']}"
    elsif data['side'] == "left"
      word = "#{data['letter']}#{data['word']}"
    end
    word = word.downcase

    word.length > 3 && Word.find_by_word(word).present?
  end
end

app/models/seek.rb
class Seek
  def self.create(room_name, uuid)
    if opponent = REDIS.spop(room_name)
      Game.start(uuid, opponent)
    else
      REDIS.sadd(room_name, uuid)
    end
  end

  def self.remove(room_name, uuid)
    REDIS.srem(room_name, uuid)
  end

  def self.clear_all(room_name)
    REDIS.del(room_name)
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    redirect_to room_path(generate_room_name)
  end

  def show

  end

  private

  def generate_room_name
    (0...6).map { (65 + rand(26)).chr }.join
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Letters game
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = favicon_link_tag 'favicon.ico'
    %link{:href => "https://fonts.googleapis.com/css?family=Alfa+Slab+One", :rel => "stylesheet"}/
  %body{class: "#{controller_name} #{action_name }"}
    %center
      #logo_title
        %span.text
          letters
        %span.apostrophe
          = "'"
    = yield

app/views/rooms/show.html.haml
.beta-info
  %center
    beta
#friend-link
  %center
    send link to your friend to start a game:
    #room{name: params[:id]}
    .room-info
      .row
        .col-md-4
        .col-md-4
          = text_field_tag "link", room_url(params[:id]), class: "form-control room-address", onFocus:"this.select()"
%main.main
  %div
    %svg.svg-text{:height => "200", :width => "1500", :xmlns => "http://www.w3.org/2000/svg"}
      %defs
        %symbol#stroke-2
          %text#word.bold.game_word{:fill => "none", "paint-order" => "stroke fill", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => ".1em", "text-anchor" => "middle", :x => "50%", :y => "67%"}
        %symbol#fill-2
          %text.bold.game_word{"text-anchor" => "middle", :x => "50%", :y => "60%"}
      %g.svg-text__shaded__stroke{:stroke => "#206891"}
        %use{:filter => "url(#drop-stroke-shadow)", :opacity => "0.5", "xlink:href" => "#stroke-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "5%"}
        %use{"xlink:href" => "#stroke-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "3%"}
        %use{"xlink:href" => "#stroke-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "2%"}
        %use{"xlink:href" => "#stroke-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "1%"}
        %use{:stroke => "#39b1f7", "xlink:href" => "#stroke-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink"}
      %g{:fill => "#84a4b5"}
        %use.svg-text__shaded{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "7%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "6.5%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "6%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "5.5%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "5%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "4.5%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "4%"}
        %use{"xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "3.5%"}
        %use{:fill => "white", "xlink:href" => "#fill-2", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "3%"}
#opponent-move
  %center
    Waiting for opponent move ...
#controles{style: "display:none"}
  .row
    .col-md-4
    .col-md-4
      .col-md-2
      .col-md-3
        %a#button{onclick: "submitLetterForm('left')"}
          %span Add to left
        / = button_tag "Add to the left", class: "btn btn-block btn-primary" , onclick: "submitLetterForm('left')"
      .col-md-2
        = text_field_tag "letter", nil, maxlength: 1,class: "form-control", id: "letter_input", placeholder: "letter"
      .col-md-3
        %a#button{onclick: "submitLetterForm('right')"}
          %span Add to right
        / = button_tag "Add to the right", class: "btn btn-primary btn-block", onclick: "submitLetterForm('right')"
  .row#check-btn
    .col-md-4
    .col-md-4
      .col-md-2
      .col-md-8
        = button_tag "Check oponnent", onclick: "checkOpponent()", class: "btn btn-block btn-warning"
.row{style: "margin-top: 20px"}
  .col-md-4
  .col-md-4
    .col-md-2
    .col-md-8
      = render partial: "shared/rules"
%center
  #messages
:javascript
  function submitLetterForm(side){
    letter = $("#letter_input").val();
    if (letter != ""){
      word = $(".game_word").first().text()
      App.addLetter(side, letter, word);
      $("#letter_input").val("");
      $("#letter_input").focus();
      App.hideControles()
      PageTitleNotification.Off();
      App.favicon.badge('');
    }
  }

  function checkOpponent(){
   word = $(".game_word").first().text()
   App.checkOpponent(word);
   App.hideControles()
  }

app/views/shared/_rules.haml
%center
  %a#game-rules{href: "#", "data-target" => "#rulesModal", "data-toggle" => "modal"}
    = "Read game rules"

#rulesModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Letters game rules
      .modal-body
        %h5 Turn
        %p In your turn, you can add a letter on the right or on the left side of existing set of letters or check your opponent (see Checking Opponent below). While adding new letter you have to remember about the following:
        %li
          Constructed set of letters must be a part of some existing word (in Oxford dictionary). There must be a possibility to create a word from letters containing your new letter.
          Lets say there is already a
          %b TTL
          in front of you. You can (for example) add a
          %b O
          on the left, because it will form a
          %b OTTL
          which may be a part of BOTTLE. You can also add a
          %b E
          on the left because it will create a
          %b ETTL
          which may be a part of KETTLE.
          There are usually may possibilities but remember that you have to create a string that can be a part of some word.
        %br
        %h5 Winning/Loosing
        %p Player looses when he finishes the word or when he is being checked by opponent and cannot give correct answer.
        %li
          Finishing the word is when you add your letter and a set of letters are a word.
          For example: there is a
          %b FLO
          in front of you. You wanted to add a
          %b W
          on the right, because FLOW is a port of FLOWER. But a
          %b FLOW
          is also a word itself. You loose!
        %br
        %h5 Checking your opponent
        %p
          Lets say there was a
          %b BICYCL
          on the board and your opponent has added an
          %b O.
          You now have a
          %b BICYCLO
          in front of you. The best what you can do is to check your opponent, because BICYCLO is not a part of any existing word thats why your opponent will loose. Of course if your opponent would provide a word that a BICYCLO is a part of - you would be the one who looses.
        %br
        %h5 Letters low limit
        3-letters words dont count. It means that if you create a TEA you will not loose.

      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/welcome/index.html.erb
<div id="chessboard" style="width: 400px"></div>
<div id="messages"></div>